# -*- coding: utf-8 -*-
"""ExplainingOaSaMaipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q8Dozl6yuP_hvp6w2mAMfDkBPW2BWEuz
"""

CpfOaSaMaDict = {
        "35 & below": "The ration as follows - Oa [0.6217] Sa [0.1621] Ma [0.2162].",
        "Above 35 to 45": "The ration as follows - Oa [0.5677] Sa [0.1891] Ma [0.2432].",
        "Above 45 to 50": "The ration as follows - Oa [0.5136] Sa [0.2162] Ma [0.2702].",
        "Above 50 to 55": "The ration as follows - Oa [0.4055] Sa [0.3108] Ma [0.2837].",
        "Above 55 to 60": "The ration as follows - Oa [0.4286] Sa [0.1964] Ma [0.375].",
        "Above 60 to 65": "The ration as follows - Oa [0.1893] Sa [0.2432] Ma [0.5675].",
        "Above 65 to 70": "The ration as follows - Oa [0.0715] Sa [0.1785] Ma [0.75].",
        "Above 70 above": "The ration as follows - Oa [0.08] Sa [0.08] Ma [0.84].",
        "Explanatory": 'Note that rates are based on ratio, you may simply calculate your allocation by formulating in this manner; [OA allocation = CPF contribution * Oa ratio].',
        "Example": "If the CPF contribution of an employee (30 years old) is $100, the allocation of his CPF contribution will be computed as: $62.17 = 100 x 0.6217.",
        "Identification": "Oa [Refers to Ordinary Account] Sa [Refers to Special Account] Ma [Refers to Medisave Account]."
    }
ExplanationList = [
        "Oa - refers to Ordinary accounts, which is usually used for housing payment,insurance and slight investment.",
        "Sa - refers to Special accounts and it helps Singaporean and PR during their old age.",
        "Ma - refers to MediSave account, Singaporean and PR are able to paid their medical fees or government insurances.",
    ]
CPFOaSaMaList = f"""Note that rates are based on ratio, you may simply calculate your allocation by formulating in this manner; 
    [OA allocation = CPF contribution * Oa ratio].", If the CPF contribution of an employee (30 years old) is $100, 
    the allocation of his CPF contribution will be computed as: $62.17 = 100 x 0.6217."""

LoopForLearningAboutTheOaSaMa = 0
while LoopForLearningAboutTheOaSaMa < 3:
    LearningAboutTheOaSaMa = input('''Would you like to learn more about Oa, Sa and Ma? Please either 'Yes' or 'No'
> ''').lower()
    if LearningAboutTheOaSaMa == "no":
        print("Session ended based on response.")
        break
    elif LearningAboutTheOaSaMa == "yes":
        AskUserAgeWhileLearningOASAMA = int(input(f'''Please specify your age
> '''))
        if AskUserAgeWhileLearningOASAMA <= 35:
            Response1PartA = CpfOaSaMaDict.get("Explanatory")
            Response1PartB = CpfOaSaMaDict.get("35 & below")
            print(Response1PartA)
            print(Response1PartB)
            OaSaMaDifference = input(f'''To learn more about the difference between OA, SA and MA allocation type 'Continue' or 'End'
> ''').lower()
            if OaSaMaDifference == "end":
                print("Session ended based on response.")
                break
            elif OaSaMaDifference == "continue":
                for LoopOaSaMaDifference in ExplanationList:
                    print(LoopOaSaMaDifference)
                break
        elif AskUserAgeWhileLearningOASAMA <= 45:
            Response1PartA = CpfOaSaMaDict.get("Explanatory")
            Response1PartB = CpfOaSaMaDict.get("Above 35 to 45")
            print(Response1PartA)
            print(Response1PartB)
            OaSaMaDifference = input(f'''To learn more about the difference between OA, SA and MA allocation type 'Continue' or 'End'
> ''').lower()
            if OaSaMaDifference == "end":
                print("Session ended based on response.")
                break
            elif OaSaMaDifference == "continue":
                for LoopOaSaMaDifference in ExplanationList:
                    print(LoopOaSaMaDifference)
                break
        elif AskUserAgeWhileLearningOASAMA <= 50:
            Response1PartA = CpfOaSaMaDict.get("Explanatory")
            Response1PartB = CpfOaSaMaDict.get("Above 45 to 50")
            print(Response1PartA)
            print(Response1PartB)
            OaSaMaDifference = input(f'''To learn more about the difference between OA, SA and MA allocation type 'Continue' or 'End'
> ''').lower()
            if OaSaMaDifference == "end":
                print("Session ended based on response.")
                break
            elif OaSaMaDifference == "continue":
                for LoopOaSaMaDifference in ExplanationList:
                    print(LoopOaSaMaDifference)
                break
        elif AskUserAgeWhileLearningOASAMA <= 55:
            Response1PartA = CpfOaSaMaDict.get("Explanatory")
            Response1PartB = CpfOaSaMaDict.get("Above 50 to 55")
            print(Response1PartA)
            print(Response1PartB)
            OaSaMaDifference = input(f'''To learn more about the difference between OA, SA and MA allocation type 'Continue' or 'End'
> ''').lower()
            if OaSaMaDifference == "end":
                print("Session ended based on response.")
                break
            elif OaSaMaDifference == "continue":
                for LoopOaSaMaDifference in ExplanationList:
                    print(LoopOaSaMaDifference)
                break
        elif AskUserAgeWhileLearningOASAMA <= 60:
            Response1PartA = CpfOaSaMaDict.get("Explanatory")
            Response1PartB = CpfOaSaMaDict.get("Above 55 to 60")
            print(Response1PartA)
            print(Response1PartB)
            OaSaMaDifference = input(f'''To learn more about the difference between OA, SA and MA allocation type 'Continue' or 'End'
> ''').lower()
            if OaSaMaDifference == "end":
                print("Session ended based on response.")
                break
            elif OaSaMaDifference == "continue":
                for LoopOaSaMaDifference in ExplanationList:
                    print(LoopOaSaMaDifference)
                break
        elif AskUserAgeWhileLearningOASAMA <= 65:
            Response1PartA = CpfOaSaMaDict.get("Explanatory")
            Response1PartB = CpfOaSaMaDict.get("Above 60 to 65")
            print(Response1PartA)
            print(Response1PartB)
            OaSaMaDifference = input(f'''To learn more about the difference between OA, SA and MA allocation type 'Continue' or 'End'
> ''').lower()
            if OaSaMaDifference == "end":
                print("Session ended based on response.")
                break
            elif OaSaMaDifference == "continue":
                for LoopOaSaMaDifference in ExplanationList:
                    print(LoopOaSaMaDifference)
                break
        elif AskUserAgeWhileLearningOASAMA <= 70:
            Response1PartA = CpfOaSaMaDict.get("Explanatory")
            Response1PartB = CpfOaSaMaDict.get("Above 65 to 70")
            print(Response1PartA)
            print(Response1PartB)
            OaSaMaDifference = input(f'''To learn more about the difference between OA, SA and MA allocation type 'Continue' or 'End'
> ''').lower()
            if OaSaMaDifference == "end":
                print("Session ended based on response.")
                break
            elif OaSaMaDifference == "continue":
                for LoopOaSaMaDifference in ExplanationList:
                    print(LoopOaSaMaDifference)
                break
        elif AskUserAgeWhileLearningOASAMA >= 71:
            Response1PartA = CpfOaSaMaDict.get("Explanatory")
            Response1PartB = CpfOaSaMaDict.get("Above 70 above")
            print(Response1PartA)
            print(Response1PartB)
            OaSaMaDifference = input(f'''To learn more about the difference between OA, SA and MA allocation type 'Continue' or 'End'
> ''').lower()
            if OaSaMaDifference == "end":
                print("Session ended based on response.")
                break
            elif OaSaMaDifference == "continue":
                for LoopOaSaMaDifference in ExplanationList:
                    print(LoopOaSaMaDifference)
                break