# -*- coding: utf-8 -*-
"""funcCPFCalcu

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q8Dozl6yuP_hvp6w2mAMfDkBPW2BWEuz
"""

def cpfCalc(age, salary):
    if (age < 55):
        eper = salary * 0.17
        epee = salary * 0.20
    elif (age >= 55) and (age <= 60):
        eper = salary * 0.145
        epee = salary * 0.15
    elif (age >= 61) and (age <= 65):
        eper = salary * 0.11
        epee = salary * 0.095
    elif (age >= 66) and (age <= 70):
        eper = salary * 0.085
        epee = salary * 0.07
    else:
        eper = salary * 0.075
        epee = salary * 0.05
    return eper, epee 


cpfCalc(17,1750)
# Func to reuse codes

age = int(input("Please enter your age: "))
salary = float(input("Please enter your salary: "))
if (salary <= 50):
    print("Salary does not required CPF contribution.")
else:
    employerC, employeeC = cpfCalc(age, salary)
    print(f"Employer's contribution:$ {employerC:.2f}")
    print(f"Employee's contribution:$ {employeeC:.2f}")
    print(f"Remaining salary:$ {salary - employeeC:.2f}")
find_out_about_contri = input("""Enter 'Yes' to find out more
about why contribution is required. 
Otherwise, 'No' to end session """).lower()
if find_out_about_contri == "yes":
    print("""CPF contributions are payable by any employee  
who are employed under a contract of service and 
are Singapore Citizens or Permanent Residents 
earning total wages of more than $50 per month.""")
else:
    print(f"Thank you for using this service, have a lovely day!")
# You may amend or create your own style of input.